- .bumpversion.cfg
- Makefile
- bootstrap/Makefile
- tests/make/project_validate_failure.bats
- tests/make/project_validate_success.bats
- updates `sh/lint` target
- adds better handling of the` PROJECT_ROOT` env var
- adds `project/validate` target 
re `project/validate` - was running into a weird permissions thing with windows + wsl + docker where docker would create the specified bind mounts but they would be empty container side. Hopefully this new target will avoid excessive head scratching should anyone else have this issue.
> Shellcheck fix

- .bumpversion.cfg
Docker hub's regex for release on tag was configured to update on single digit semver string (0.0.0 vs 00.00.00). 
The build logic has been updated, but the only way to manually re-run the build on tag is to either remove/re-add the tag or to add a new tag.
> Bumps version to 0.0.11

- .bumpversion.cfg
- Makefile
- bootstrap/Makefile
- bootstrap/Makefile.bootstrap
- `eclint/lint`:  ensures `git status -s` runs from the project root directory
- `docker/clean`: adds `docker system prune`
- `Makefile.bootstrap`: ensures `PROJECT_ROOT` env var takes precedence
> Project root fix

- .bumpversion.cfg
- Makefile
Most of our other targets are using `find` to run the target's base tool over the target project recursively. Since eclint doesn't have a dot ignore file it has to be fed results from `git ls` which, previously, was being run from the top level directory of tardigrade-ci, _not_ from the root of the project we want to actually lint. This should fix that.
a little more context. 
before: 
```
[eclint/lint]: Running eclint...
cd /ci-harness/utils && \
[ -z "" ] || (echo "untracked changes detected!" && exit 1)
git ls-files -z | grep -zv ".bats" | xargs -0 -I {} echo {}
.bumpversion.cfg
.dependabot/config.yml
.dummy_include
.editorconfig
.gitignore
.mergify.yml
.travis.yml
.yamllint.yml
CHANGELOG.md
Dockerfile
LICENSE
Makefile
README.md
bootstrap/Makefile
bootstrap/Makefile.bootstrap …
```
> Eclint fix round 2

- .bumpversion.cfg
- .editorconfig
- .pylintrc
- Dockerfile
- Makefile
- tests/make/python_format_failure.bats
- tests/make/python_format_success.bats
- tests/make/python_lint_black_failure.bats
- tests/make/python_lint_black_success.bats
- tests/make/python_lint_pylint_failure.bats
- tests/make/python_lint_pylint_success.bats
When the 'python/lint' target is executed, both black and pylint will now be executed against python files within the repo.  The changes include:
* Updating Dockerfile to change python3.7 to python3.8.
* Modifying the Makefile to add a target pylint/install and to add pylint/install to the install target.
* Modifying the Makefile's python/lint target to add a pylint command.
* Adding a .pylintrc file with max-line-length set to 88.
> Add pylint to the Makefile's python/lint target's recipe

- .bumpversion.cfg
- Makefile
- tests/make/eclint_lint_success.bats
- tests/make/python_format_success.bats
The Makefile is searching git for python files for input to pylint and black, but finds none outside of tardigrade-ci itself.  This problem exists for eclint as well.  All three Makefile targets have been fixed with this pull request.
Loren determined that the problem is caused by the logic that uses 'git ls-files' to find python files in the repo.  The dockerfile created to run tardigrade-ci's Makefile pulls in the tardigrade-ci files, then creates a subdirectory (ci-harness) for the repo 'under test'.  The 'git ls-files --cached --others --exclude-standard' will find git files in tardigrade-ci, but not in the git repo in the subdirectory (ci-harness).
To work around this problem, the tardigrade-ci Makefile needed to ignore tardigrade-ci's git files and focus on the git repo in the …
> pylint and black find no python files outside of tardigrade-ci

- .bumpversion.cfg
- Makefile
- tests/make/eclint_lint_success.bats
The prior fix to add pylint and black to the Makefile did not have all the necessary corrections for eclint.  For this fix, I tested the following scenarios and they all passed (results will be added in another comment):
- tardigrade-ci:  make bats/test
- tardigrade-modules:  make eclint/lint
- tardigrade-modules:  create the docker image and run make eclint/lint
This test scenario will now fail due to the value of PROJECT_ROOT, but that problem will be handled by another task:
- tardigrade-ci:  make eclint/lint
> Fix git path for eclint files

- .bumpversion.cfg
- .dummy_include
- Makefile
- README.md
- bootstrap/Makefile.bootstrap
- tests/make/Makefile
- tests/make/project_validate_failure.bats
This eliminates the layer of indirection where the using project
is available in the container at /ci-harness/<project_name>.
With this change, running make targets in the container is the same as
running make targets outside the container.
> Mounts current working directory to docker WORKDIR

- .bumpversion.cfg
- bootstrap/Makefile.bootstrap
- bootstrap/bin/install.sh
With the change to how the container is mounted in v0.6.0, projects would *always* retrieve the latest Makefile even when pinning an earlier version of the docker container. This could cause unexpected CI failures in work unrelated to an update of the container.
You can see an example of the failure in this PR:
* https://github.com/plus3it/terraform-aws-remote-access/pull/119
Even though the project pins tardigrade-ci 0.2.0 for the docker container, it is still receiving the latest Makefile on `make init`, which causes it to run the latest python/lint target instead of the version from 0.2.0.
> Attempts to retrieve version from Dockerfile when bootstrapping tardigrade-ci

- .bumpversion.cfg
- Makefile
TARDIGRADE_CI_PATH has logic that will resolve to a TARDIGRADE_CI_PROJECT
directory that is one of:
* A subdirectory of the current project. This is what `make init` sets up,
when it clones the tardigrade-ci project. i.e. `/<project>/` and
`/<project>/tardigrade-ci`.
* A parent/sibling directory of the current project. This allows a dev to
have a separate clone of tardigrade-ci in a parent/sibling directory,
for either local dev/test of tardigrade-ci, or just to reduce clone-sprawl
of tardigrade-ci. i.e. `/<project>/` and `/tardigrade-ci/`.
Previously, some weird behavior could occur with the docker/run target
in the second case. If the user had a local clone of tardigrade-ci (and
had not run `make init`), then the container did not have access to the
tardigrade-ci project, and so the …
> Mounts TARDIGRADE_CI_PATH to the docker container

- .travis.yml
- CHANGELOG.md
- Dockerfile
- Makefile
GitHub has begun scanning for and disabling access tokens in committed, public code (even when readonly). This broke the prior mechanism of authenticating to the GitHub API to increase rate limits.
This patch will use GITHUB_ACCESS_TOKEN if it is present in the env. If not present, anonymous authentication will be used (which is subject to a lower rate limit).
> Authenticates to GitHub API with GITHUB_ACCESS_TOKEN only if present

- .bumpversion.cfg
- CHANGELOG.md
- Dockerfile
- bootstrap/Makefile.bootstrap
* PWD is an env set by the shell. When invoked outside a shell, such as using `docker run`, PWD is not guaranteed to exist. This patch ensures PWD is set, which fixes use cases inside docker containers.
* When the project is using a build system (CodeBuild, travis-ci) that is itself running in a docker container, the file `.dockerenv` exists, so the auto-init was skipped. But these containers do not have the `/tardigrade-ci/` project contents, so `make` would fail to find any targets. Even calling `make init` explicitly would fail in this scenario. This patch ensures that auto-init will run in non-tardigrade-ci containers, so the targets will be available.
1. Setup a new project using this fork/branch:
```
mkdir test-project && cd test-project
git init
echo 'FROM …
```
> Corrects a couple use cases when operating inside docker containers

- Makefile
- tests/make/docs_lint_success.bats
The latest version of terraform-docs, v0.11.x, introduces some changes to the readme sections. To avoid requiring changes to every project that uses tardigrade-ci, this patch temporarily pins the old version.
> Pins terraform-docs to v0.10.1 to avoid requiring changes in every project

- .bumpversion.cfg
- .editorconfig
- CHANGELOG.md
- Makefile
- tests/make/.test_pylintrc
- tests/make/Makefile
- tests/make/python_lint_pylint_rcfile_failure.bats
- tests/make/python_lint_pylint_rcfile_success.bats
Depending how the makefile was run, it would not necessarily find `tardigrade-ci`'s `.pylintrc` file.  The location of the `.pylintrc` file is now specified by the variable `PYLINT_RCFILE` and by default it points to`tardigrade-ci`'s `.pylintrc`.
The `.pylintrc` file was updated to include the loadable plugin 'pylint-pytest' and there is now the capability to install python modules in addition to python scripts.
> Fix .pylintrc handling and add support for pytest linting

- .bumpversion.cfg
- Makefile
Previously, AWS_PROFILE would be set to a null value if the env was unset. That is an invalid configuration and could result in exceptions in AWS SDKs when they attempt to setup a session.
> Skips setting AWS_PROFILE when the env is not available

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
The prior version of terraform-docs left the trailing newline, so
that is what all our current docs have. The latest terraform-docs
trims all newlines from the end.
This isn't the first time terraform-docs has changed how it manages
terminating newline characters. This patch takes control of the newline
behavior by stripping all newlines, `echo "$(...)"`, and adding back
a single newline at the end, `; echo`. This way we match the current
tests and the readmes in all current projects, and we won't be subject
to future changes in terraform-docs and its behavior with terminating
newlines.
This patch also disables the "modules" and "resources" outputs of
terraform-docs v0.11.x, to avoid requiring further changes to project
readmes.
> Uses latest terraform-docs, finishing with a single empty newline

- Makefile
- bootstrap/Makefile.bootstrap
The `Dockerfile` reference in the bootstrap is hardcoded. Updated it to be an overridable variable using `TARDIGRADE_CI_DOCKERFILE ?= Dockerfile`.
> Create overridable variable for Dockerfile location.

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
- bootstrap/Makefile.bootstrap
Also suppresses the auto-init output in recursive calls to $(MAKE).
The workflow is:
1. The bootstrap sets TARDIGRADE_CI_AUTO_INIT = true
2. The bootstrap include statement executes the auto-init macro, outputs
status accordingly, and includes the tardigrade-ci Makefile
3. The tardigrade-ci Makefile *exports* TARDIGRADE_CI_AUTO_INIT = false
4. Recursive calls to $(MAKE) include the bootstrap again
5. The bootstrap include disables the auto-init macro because
TARDIGRADE_CI_AUTO_INIT != true
> Adds env that controls whether auto-init is enabled

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
The terraform-docs team is no longer providing the binary as its own release artifact. It is now only available within a tar.gz archive.
> Extracts terraform-docs from archive retrieved from github release

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
- requirements.txt
- tests/make/python_lint_pydocstyle_failure.bats
black now detects an error before pydocstyle is run, so the pydocstyle unit test fails with the newer version of black.
> Correct pydocstyle unit test for new version of black

- .travis.yml
Previously, if `docker build` failed, `docker run` would pull the latest image from dockerhub. That meant the bats/test would run on the wrong image.
This patch ensures that the test fails when the build fails, and for good measure also changes the image name in the test so it can't be pulled from dockerhub.
> Fails the test when the build fails

- .bumpversion.cfg
- CHANGELOG.md
Comparison from 0.14.0 release to current master: https://github.com/plus3it/tardigrade-ci/compare/0.14.0...master
This release is necessary as a result of a transitory dependency in cfn-lint, the `networkx` library. The networkx 2.6 release is incompatible with cfn-lint 0.50.0, currently what is released in tardigrade-ci 0.14.0. Using cfn-lint 0.50.0 and networkx 2.6.1 results in:
```
$ cfn-lint --version
Traceback (most recent call last):
File "/home/loren/.local/bin/cfn-lint", line 5, in <module>
from cfnlint.__main__ import main
File "/home/loren/.local/lib/python3.9/site-packages/cfnlint/__init__.py", line 9, in <module>
from cfnlint.graph import Graph
File "/home/loren/.local/lib/python3.9/site-packages/cfnlint/graph.py", line 10, in <module>
from networkx import networkx …
```
> Bumps version to 0.14.1

- .bumpversion.cfg
- CHANGELOG.md
- INTEGRATION_TESTING.md
- Makefile
- tests/make/pytest_failure.bats
- tests/make/pytest_success.bats
- tests/make/terraform_pytest_failure.bats
- tests/make/terraform_pytest_success.bats
- tests/terraform_pytest/mockstack.tf
- tests/terraform_pytest/test_terraform_install.py
Adds the new target "pytest/%" and fixes an error in the integration test utility that occurs when a test fails.
> Update pytest targets

- .bumpversion.cfg
- .travis.yml
- CHANGELOG.md
- tests/terraform_pytest/mockstack.tf
The Travis workflow only specified specific lints, ec and shell linting.  With a previous change for recursive Terraform linting, this meant Terraform lint errors in tardigrade-ci files weren't caught until after a new version of tardigrade-ci was released and a repo using that version contained Terraform files.
The Travis workflow will now perform a `make lint` to perform all lints that it currently handles.
> Lint all in Travis workflow

- .bumpversion.cfg
- CHANGELOG.md
- Dockerfile
- Makefile
Prior to this patch, files created in the docker volume mounts were
owned by root, which causes permissions issues when accessing those
files outside the container.
This was particularly evident when running the mockstack/pytest target
(which operates inside the container), followed by running the terraform/pytest
target (which operates outside the container).
With this patch, files created in the mounted filesystem will be owned by
the user running the docker container, so there should no longer be
any permissions issues.
> Creates a non-root user in docker image and passes user context when building image

- .bumpversion.cfg
- .github/workflows/dependabot_hack.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- entrypoint.sh
The user that builds the tardigrade-ci container and the user that runs
the tardigrade-ci container (or containers built from it) must have the
same UID, or permissions issues will occur.
This patch uses fixuid in the tardigrade-ci entrypoint to fix this
issue. Fixuid checks the user running the container and chowns any
file or directory owned by a specified user/group in its configuration.
This ensures the user has permissions to those files and directories.
> Uses fixuid in entrypoint to fix permissions issues with bindmounts

- .bumpversion.cfg
- CHANGELOG.md
- tests/terraform_pytest/mockstack.tf
Specifically, the following services were added to `mockstack.tf`:
- Cloudtrail
- Directory Services
- Route53 Resolver
Route53 was changed to use a moto port rather than a LocalStack port.
> Add moto-only support for additional services

- .bumpversion.cfg
- CHANGELOG.md
- INTEGRATION_TESTING.md
- tests/terraform_pytest/conftest.py
Previously the use of both of these options would cause an exit.
> Issue warning if PYTEST_ARGS --only-moto and --nomock used

- .bumpversion.cfg
- CHANGELOG.md
- tests/terraform_pytest/docker-compose-localstack.yml
MOTO_DOCKER_NETWORK_NAME has been added to the list of environment variables passed to LocalStack in the `docker-compose-localstack.yml` file.  This environment variable is used by moto to determine the network IP address for `moto_server` when running in a docker container.
> Add MOTO_DOCKER_NETWORK_NAME to docker compose file

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
Previously, if a caller named their tardigrade-ci makefile any non-default
name, e.g. Makefile.foo, while also having a default-named makefile, e.g. Makefile,
and invoked `make -f Makefile.foo`, the sub-makes would invoke the default
makefile and not the tardigrade-ci makefile.
This patch updates all sub-make calls to specify the file to use with
make. This is accomplished by determing the current Makefile:
```
THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
```
And then updating the SELF variable to `$(MAKE) -f $(THIS_MAKEFILE)`.
All sub-makes are modifed to use the updated `$(SELF)` variable instead
of directly using `$(MAKE)`.
This allows a caller to name their tardigrade-ci makefile anything,
e.g. Makefile.foo, and call all the targets using `make -f Makefile.foo`.
> Allows callers to use any name for the Makefile, set with `make -f`

- .bumpversion.cfg
- CHANGELOG.md
- Makefile
- tests/make/ec_lint_success.bats
- tests/make/json_format_failure.bats
Link to see changes on master compared to last release: https://github.com/plus3it/tardigrade-ci/compare/0.21.9...master
> Standardizes all "find" logic using "git ls-files" to honor .gitignore

- CHANGELOG.md
- Dockerfile
The update takes a very long time and quite a bit of space, and the reason we added the update in the first place is no longer relevant. The version of cfn-lint has the necessary specs for all our templates.
> Uses specs bundled with cfn-lint
